# Generated by Django 5.0.3 on 2025-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0002_simplify_position_kinds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hold',
            new_name='stockman_ho_status_d81358_idx',
            old_name='stockman_ho_status_aaa8ec_idx',
        ),
        migrations.RenameIndex(
            model_name='hold',
            new_name='stockman_ho_content_44181c_idx',
            old_name='stockman_ho_content_8d3e50_idx',
        ),
        migrations.RenameIndex(
            model_name='hold',
            new_name='stockman_ho_status_f46aaf_idx',
            old_name='stockman_ho_status_f7b3b2_idx',
        ),
        migrations.RenameIndex(
            model_name='move',
            new_name='stockman_mo_quant_i_cef5d1_idx',
            old_name='stockman_mo_quant_i_01d0c9_idx',
        ),
        migrations.RenameIndex(
            model_name='move',
            new_name='stockman_mo_timesta_79df8d_idx',
            old_name='stockman_mo_timesta_2d4ce4_idx',
        ),
        migrations.RenameIndex(
            model_name='quant',
            new_name='stockman_qu_content_44478d_idx',
            old_name='stockman_qu_content_09d8a3_idx',
        ),
        migrations.RenameIndex(
            model_name='quant',
            new_name='stockman_qu_target__e912cb_idx',
            old_name='stockman_qu_target__4e259e_idx',
        ),
        migrations.RenameIndex(
            model_name='quant',
            new_name='stockman_qu_positio_75028c_idx',
            old_name='stockman_qu_positio_73cc97_idx',
        ),
        migrations.AddField(
            model_name='position',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se True, esta é a posição padrão para novos Quants.', verbose_name='Posição padrão'),
        ),
    ]
