# Generated by Django 5.0.3 on 2025-12-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0004_initial_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hold',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['timestamp'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='quant',
            options={'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
    ]
