# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stockman', '0005_alter_hold_options_alter_move_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['timestamp'], 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
        migrations.AlterModelOptions(
            name='quant',
            options={'verbose_name': 'Saldo', 'verbose_name_plural': 'Saldos'},
        ),
        migrations.AlterField(
            model_name='hold',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID do Produto'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='purpose_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Finalidade'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='purpose_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Finalidade'),
        ),
        migrations.AlterField(
            model_name='move',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='move',
            name='quant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='stockman.quant', verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='move',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Referência'),
        ),
        migrations.AlterField(
            model_name='move',
            name='reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Referência'),
        ),
        migrations.AlterField(
            model_name='move',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='quant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='quant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='quant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddConstraint(
            model_name='quant',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('content_type', 'object_id', 'position', 'target_date'), name='unique_quant_coordinate_no_batch'),
        ),
    ]
