# Generated by Django 5.2.11 on 2026-02-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stockman', '0006_alter_move_options_alter_quant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('min_quantity', models.DecimalField(decimal_places=3, help_text='Alerta dispara quando disponível < este valor', max_digits=12, verbose_name='Quantidade Mínima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Último disparo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Produto')),
                ('position', models.ForeignKey(blank=True, help_text='Vazio = soma de todas as posições', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.CRAFTSMAN_POSITION_MODEL, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='stockman_st_content_1d5762_idx'), models.Index(fields=['is_active'], name='stockman_st_is_acti_f03411_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'position'), name='unique_stock_alert_per_product_position')],
            },
        ),
    ]
