# Generated by Django 5.2.11 on 2026-02-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stockman', '0007_add_stock_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador único do lote. Usado como Quant.batch.', max_length=50, unique=True, verbose_name='Código do Lote')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Data de Produção')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Último dia em que o lote pode ser vendido/utilizado', null=True, verbose_name='Data de Validade')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['expiry_date', 'production_date'],
            },
        ),
        migrations.AddField(
            model_name='quant',
            name='batch_ref',
            field=models.ForeignKey(blank=True, help_text='Lote rastreável com metadados (validade, fornecedor, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quants', to='stockman.batch', verbose_name='Referência de Lote'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product_type', 'product_id'], name='stockman_ba_product_d6ba47_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='stockman_ba_expiry__8ec17e_idx'),
        ),
    ]
